#!/usr/bin/env bash
#

#A script to show current power profile

current_profile=$(/usr/bin/powerprofilesctl get)
if [ $current_profile = performance ]
then
   echo ""
elif [ $current_profile = balanced ]
then
   echo ""
else
   echo ""
fi

